SENDGRID_PASSWORD: 1rx0ce7k4112
SENDGRID_USERNAME: app39763621@heroku.com
AWS_ACCESS_KEY_ID: AKIAJ5RK3ZH7MOA3IRYQ
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: jonathan-bloccit-development
production:
  AWS_BUCKET: jonathan-bloccit-production
# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
